cipher: drop p8inf->broken flag check
struct pkcs8_priv_key_info_st is now opaque as of OpenSSL 1.1
so we cannot look directly at its flags going forward.

./cipher.c: In function ‘cipher_rsa_decrypt’: ./cipher.c:73:11: error: dereferencing pointer to incomplete type ‘PKCS8_PRIV_KEY_INFO {aka struct
pkcs8_priv_key_info_st}’
  if (p8inf->broken)
           ^

Signed-off-by: Bob Copeland <copeland@lastpass.com>