Fix compiling when using LibreSSL
Fix undefined reference to `HMAC_CTX_new' and `HMAC_CTX_free' when using
LibreSSL instead of OpenSSL.

Signed-off-by: Björn Ketelaars <bjorn.ketelaars@hydroxide.nl>