make: don't require using make, as it is a compat wrapper for cmake
Running part of the build process in the toplevel Makefile means that
users are forbidden to use cmake directly in order to get more control
over the cmake arguments, and are also forbidden to use alternative
cmake backends without having the Make program installed.

It also causes unpredictable issues that must be worked around by every
downstream consumer, when the established cmake build process that is
supposed to work, aborts with:

/build/lastpass-cli-git/src/lastpass-cli/blob.c:42:10: fatal error: version.h: No such file or directory
 #include "version.h"
          ^~~~~~~~~~~
compilation terminated.

Fixes https://github.com/eli-schwartz/pkgbuilds/pull/12

Signed-off-by: Eli Schwartz <eschwartz@archlinux.org>